stages:
  - code_quality
  - tests

flake8-lint:
  stage: code_quality
  image: python:3.12
  before_script:
    - pip install flake8
  allow_failure: false
  script:
    - flake8 .

.test_template:
  stage: tests
  image: python:3.12
  allow_failure: false
  services:
    - name: mysql:8.0
      alias: db
  variables:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: event_gate_test
    MYSQL_USER: root
    MYSQL_PASSWORD: root_password
    DB_NAME: event_gate_test
    DB_USER: root
    DB_PASSWORD: root_password
    DB_HOST: db
    DB_PORT: 3306
  before_script:
    - pip install -r ./event_gate/requirements.txt
    - |
      while ! mysqladmin ping -h db --silent; do
        echo "Waiting for database to be ready..."
        sleep 2
      done
    - python ./event_gate/manage.py migrate


profiles_unit_test:
  extends: .test_template
  script:
    - python ./event_gate/manage.py test ./event_gate/profiles/tests/unit/

profiles_functional_test:
  extends: .test_template
  script:
    - python ./event_gate/manage.py test ./event_gate/profiles/tests/functional/
