stages:
  - code_quality
  - tests

flake8-lint:
  stage: code_quality
  image: python:3.12
  before_script:
    - pip install flake8
  allow_failure: false
  script:
    - flake8 .

.test_template:
  stage: tests
  image: python:3.12
  allow_failure: false
  services:
    - name: mysql:8.0
      alias: db
  variables:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: event_gate_test
    MYSQL_USER: root
    MYSQL_PASSWORD: root_password
  before_script:
    - apt-get update && apt-get install -y wget
    - wget https://github.com/jwilder/dockerize/releases/latest/download/dockerize-linux-amd64-v0.6.1.tar.gz
    - tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
    - pip install -r ./event_gate/requirements.txt
    - dockerize -wait tcp://db:3306 -timeout 30s
    - python ./event_gate/manage.py migrate

profiles_unit_test:
  extends: .test_template
  script:
    - python ./event_gate/manage.py test ./event_gate/profiles/tests/unit/

profiles_functional_test:
  extends: .test_template
  script:
    - python ./event_gate/manage.py test ./event_gate/profiles/tests/functional/
