# Generated by Django 5.1.1 on 2024-11-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_bio_alter_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
